# Use the hash sign to prefix a comment
# +---------------- minute (0 - 59)
# |  +------------- hour (0 - 23)
# |  |  +---------- day of month (1 - 31)
# |  |  |  +------- month (1 - 12)
# |  |  |  |  +---- day of week (0 - 7) (Sunday=0 or 7)
# |  |  |  |  |
# *  *  *  *  *  command to be executed
#--------------------------------------------------------------------------

name: Information Retrieval

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  acquire-and-push:
    name: Collect periodic weather forecast
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3

    - name: Collect 60h weather forecast image
      run: |
        curl -s "https://old.meteo.pl//um/ramka_um_city_pl.php" > ramka.html
        cat ramka.html | grep -oP '(?<=var UM_SYYYY=")[0-9]+' | tr -d '\n' > fcstdate.txt
        cat ramka.html | grep -oP '(?<=var UM_SMM=")[0-9]+' | tr -d '\n' >> fcstdate.txt
        cat ramka.html | grep -oP '(?<=var UM_SDD=")[0-9]+' | tr -d '\n' >> fcstdate.txt
        cat ramka.html | grep -oP '(?<=var UM_SST=")[0-9]+' | tr -d '\n' >> fcstdate.txt
        rm ramka.html
        wget "https://www.meteo.pl/um/metco/mgram_pict.php?ntype=0u&fdate=$(cat fcstdate.txt)&row=466&col=232&lang=pl" -O krakow/60.png
        ./commit.sh
